### ISSUE TITLE
single-select button group is causing unique key warning

### ISSUE THREAD

**Issue by erikcw** [reagent-project/reagent-forms#55]
After adding a `:single-select` button to a form my console started getting flooded with the following warnings:

```clojure
[bind-fields [:div.btn-group {:field :single-select :id :data.geo_type}
                          [:button.btn.btn-default {:key "no-geo"} "None"]
                          [:button.btn.btn-default {:key "state"} "State"]
                          [:button.btn.btn-default {:key "cite"} "City"]
                          [:button.btn.btn-default {:key "zip-codes"} "Zip Codes"]]  campaigns]
```

```
Warning: Every element in a seq should have a unique :key (in reagent_forms$core$selection_group). Value: ([#<function (){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [type,cljs.core.merge.call(null,new cljs.core.PersistentArrayMap.fromArray([new cljs.core.Keyword(null,"class","class",-2030961996),(cljs.core.truth_(cljs.core.get.call(null,cljs.core.deref.call(null,selections),key))?"active":null),(function (){var or__4333__auto__ = touch_event;
if(cljs.core.truth_(or__4333__auto__)){
return or__4333__auto__;
} else {
return new cljs.core.Keyword(null,"on-click","on-click",1632826543);
}
})(),handle_click_BANG_], true, false),attrs),body], null);
}>] [#<function (){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [type,cljs.core.merge.call(null,new cljs.core.PersistentArrayMap.fromArray([new cljs.core.Keyword(null,"class","class",-2030961996),(cljs.core.truth_(cljs.core.get.call(null,cljs.core.deref.call(null,selections),key))?"active":null),(function (){var or__4333__auto__ = touch_event;
if(cljs.core.truth_(or__4333__auto__)){
return or__4333__auto__;
} else {
return new cljs.core.Keyword(null,"on-click","on-click",1632826543);
}
})(),handle_click_BANG_], true, false),attrs),body], null);
}>] [#<function (){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [type,cljs.core.merge.call(null,new cljs.core.PersistentArrayMap.fromArray([new cljs.core.Keyword(null,"class","class",-2030961996),(cljs.core.truth_(cljs.core.get.call(null,cljs.core.deref.call(null,selections),key))?"active":null),(function (){var or__4333__auto__ = touch_event;
if(cljs.core.truth_(or__4333__auto__)){
return or__4333__auto__;
} else {
return new cljs.core.Keyword(null,"on-click","on-click",1632826543);
}
})(),handle_click_BANG_], true, false),attrs),body], null);
}>] [#<function (){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [type,cljs.core.merge.call(null,new cljs.core.PersistentArrayMap.fromArray([new cljs.core.Keyword(null,"class","class",-2030961996),(cljs.core.truth_(cljs.core.get.call(null,cljs.core.deref.call(null,selections),key))?"active":null),(function (){var or__4333__auto__ = touch_event;
if(cljs.core.truth_(or__4333__auto__)){
return or__4333__auto__;
} else {
return new cljs.core.Keyword(null,"on-click","on-click",1632826543);
}
})(),handle_click_BANG_], true, false),attrs),body], null);
}>])
```

reagent 0.5
reagent-forms 0.5.1
React 0.13.1

**Comment by yogthos** [comment]
Looks like key metadata is needed fix the warnings. It shouldn't really affect functionality or performance unless you have a very large number of buttons.

**Comment by jindrichmynarz** [comment]
I came across this issue in the latest release of reagent-forms (0.5.4). While I agree it should not affect performance in most cases, having the console free of warnings is better. Is there a plan to fix it?

**Comment by yogthos** [comment]
Yeah, I agree that the warnings need to be fixed here. :)

**Comment by yogthos** [comment]
should be fixed in `0.5.5`

**Comment by jindrichmynarz** [comment]
At first I thought `0.5.5` does not fix the issue, but then I realized I forgot to `lein clean`. Thanks for this fix!

**Comment by yogthos** [comment]
excellent ;)
